spring:
  profiles:
    active: local

  datasource:
    driverClassName: ${secrets.database.driver}
    url: ${secrets.database.url}
    username: ${secrets.database.username}
    password: ${secrets.database.password}

  jpa:
    database-platform: ${secrets.jpa.platform}
    hibernate.ddl-auto: ${secrets.jpa.mode}

  mail:
    host: ${secrets.mail.host}
    port: ${secrets.mail.port}
    username: ${secrets.mail.username}
    password: ${secrets.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /docs
