#file: noinspection SpringBootApplicationYaml
secrets:
  database:
    driver:
    url:
    username:
    password:

  jpa:
    platform:
    mode:

  mail:
    host:
    port:
    username:
    password:
