spring:
  profiles:
    active: local

  datasource:
    driverClassName: ${secrets.database.driver}
    url: ${secrets.database.url}
    username: ${secrets.database.username}
    password: ${secrets.database.password}

  jpa:
    database-platform: ${secrets.jpa.platform}
    hibernate.ddl-auto: ${secrets.jpa.mode}

server:
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /docs
